name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["src/Foundation.Shared"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Install dependencies
        run: |
          cd ${{matrix.folder}}
          dotnet restore
      - name: Build
        run: |
          cd ${{matrix.folder}}
          dotnet build --configuration Release --no-restore
